version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <your-ecr-repo>
  build:
    commands:
      - echo Building Docker image...
      - docker-compose up -d
  post_build:
    commands:
      - echo Build complete.
